### ISSUE TITLE
ui css：max-height < min-height

### ISSUE THREAD

**Issue by 1751660300** [flexxui/flexx#746]
hello

i use vbox and create more label in it, then i want set 1080px for max-height，but this height is not i want
Because of the min-height is 2826px，i try to update min-height value, but i failed 

I'd like to know how

Finally, thank you for answering so many questions.

**Comment by almarklein** [comment]
Do you perhaps have a minimal code example to demonstrate what you mean?

**Comment by 1751660300** [comment]
ok, this example, you will know problem click btn for box css, result 
```css
element.style {
    max-height: 1080px;
    min-width: 12px;
    max-width: 1e9px;
    min-height: 2798px;
    flex-grow: 0;
    flex-shrink: 1;
    margin-top: 4px;
    padding: 1px;
}
```
```py
from flexx import flx


class MyApp(flx.Widget):

    def init(self):
        with flx.VBox():
            self.btn = flx.Button(text="测试")
            self.box = flx.VBox(style="max-height: 1080px")
            flx.VBox(flex=1)

    @flx.action
    def add_div(self, text):
        flx.Label(text=text, parent=self.box)

    @flx.reaction("btn.pointer_click")
    def add_ra(self, *event):
        for i in range(100):
            self.add_div(str(i))

app = flx.App(MyApp)
app.launch('app')
flx.run()
```
